CREATE TABLE users (
  id UUID PRIMARY KEY,
  name VARCHAR(100),
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created TIMESTAMP NOT NULL,
  modified TIMESTAMP NOT NULL,
  last_login TIMESTAMP NOT NULL,
  token VARCHAR(1024) NOT NULL,
  is_active BOOLEAN NOT NULL
);

CREATE TABLE phones (
  id UUID PRIMARY KEY,
  number VARCHAR(30) NOT NULL,
  city_code VARCHAR(10) NOT NULL,
  country_code VARCHAR(10) NOT NULL,
  user_id UUID NOT NULL,
  CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(id)
);
